---
name: pull-request
on:
  pull_request:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    #- name: Static tests
    #  run: |

    - name: Buildah Action
      id: buildah-build
      if: steps.image_tags.outputs.IMAGE_TAGS
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ vars.IMAGE_NAME }}
        tags: latest
        containerfiles: Containerfile

    #- name: Test image
    #  run: |
